# Generated by Django 6.0.5 on 2026-05-06 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='العنوان الفرعي')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن الكتاب')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ISBN')),
                ('archive_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأرشفة')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='الناشر')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة النشر')),
                ('language', models.CharField(blank=True, max_length=60, verbose_name='اللغة')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم المؤلف')),
                ('biography', models.TextField(blank=True, verbose_name='نبذة عن المؤلف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='صورة المؤلف')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الوفاة')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='البلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='api_author_full_na_fbe52f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض')),
                ('is_primary', models.BooleanField(default=False, verbose_name='مؤلف رئيسي')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='api.author', verbose_name='المؤلف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='api.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'مؤلف الكتاب',
                'verbose_name_plural': 'مؤلفو الكتب',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='api.BookAuthor', to='api.author', verbose_name='المؤلفون'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('copy_number', models.CharField(max_length=50, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('borrowed', 'تم اعارته'), ('missing', 'غير موجود'), ('damaged', 'متضرر'), ('reserved', 'محجوز')], db_index=True, default='available', max_length=20, verbose_name='حالة النسخة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='api.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'نسخة كتاب',
                'verbose_name_plural': 'نسخ الكتب',
                'ordering': ['book__title', 'copy_number'],
            },
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to='books/files/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'صورة'), ('doc', 'مستند'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الملف')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'ملف كتاب',
                'verbose_name_plural': 'ملفات الكتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibrarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='الرابط المختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.librarysection', verbose_name='القسم الأب')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.librarysection', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإعارة')),
                ('due_date', models.DateField(verbose_name='تاريخ الإرجاع المتوقع')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('status', models.CharField(choices=[('active', 'سارية'), ('returned', 'مُعادة'), ('overdue', 'متأخرة'), ('canceled', 'ملغاة')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_loans', to=settings.AUTH_USER_MODEL, verbose_name='المستعير')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.bookcopy', verbose_name='نسخة الكتاب')),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_loans', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
            options={
                'verbose_name': 'إعارة',
                'verbose_name_plural': 'الإعارات',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='رقم البطاقة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الرف')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الرف')),
                ('position', models.CharField(choices=[('top', 'أعلى'), ('bottom', 'أسفل'), ('side', 'جانبي'), ('front', 'أمامي'), ('back', 'خلفي'), ('custom', 'مخصص')], default='custom', max_length=20, verbose_name='مكان الرف')),
                ('description', models.TextField(blank=True, verbose_name='وصف الرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رف',
                'verbose_name_plural': 'الأرفف',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='api_shelf_code_7aa760_idx'), models.Index(fields=['name'], name='api_shelf_name_405b8b_idx')],
            },
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='api.shelf', verbose_name='الرف'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.shelf', verbose_name='الرف'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author'), name='unique_book_author'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('book',), name='unique_primary_author_per_book'),
        ),
        migrations.AddIndex(
            model_name='librarysection',
            index=models.Index(fields=['name'], name='api_library_name_f2f096_idx'),
        ),
        migrations.AddIndex(
            model_name='librarysection',
            index=models.Index(fields=['slug'], name='api_library_slug_705f21_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='api_loan_status_bf8338_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='api_loan_due_dat_b8d1cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('copy',), name='unique_active_loan_per_copy'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status'], name='api_bookcop_status_0d554e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['copy_number'], name='api_bookcop_copy_nu_7fb165_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(fields=('book', 'copy_number'), name='unique_copy_number_per_book'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='api_book_title_dc9757_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='api_book_slug_b10dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='api_book_isbn_68620f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['archive_number'], name='api_book_archive_05dbfa_idx'),
        ),
    ]
