"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kqa1m^gybno=gjw6w5o)1)#57^hvp+1xgd0%90vgp-+m(j&xeg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django_filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "api",
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



REPORTS_PDF_FONT_PATH = BASE_DIR / "assets" / "fonts" / "DejaVuSans.ttf"



STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


JAZZMIN_SETTINGS = {
    "site_title": "إدارة المكتبة",
    "site_header": "نظام إدارة المكتبة",
    "site_brand": "نظام ادارة المكتبة",
    "site_logo": None,
    "login_logo": None,
    
    "welcome_sign": "مرحباً بك في نظام إدارة المكتبة",

    "copyright": "نظام إدارة المكتبة © 2026",

    "search_model": [
        "auth.User",
        "api.Book",
        "api.Author",
        "api.LibrarySection",
        "api.BookCopy",
        "api.Loan",
    ],

    "topmenu_links": [
        {
            "name": "الرئيسية",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "التقارير",
            "url": "/admin/reports/",
            "new_window": False,
        },
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": [
        "api",
        "api.book",
        "api.bookcopy",
        "api.author",
        "api.librarysection",
        "api.loan",
    ],

    "icons": {
        "auth": "fas fa-users-cog",

        "api.Book": "fas fa-book",
        "api.BookCopy": "fas fa-copy",
        "api.Author": "fas fa-feather",
        "api.LibrarySection": "fas fa-folder-open",
        "api.Shelf": "fas fa-layer-group",
        "api.BookFile": "fas fa-file-pdf",
        "api.Loan": "fas fa-handshake",
        "api.MemberProfile": "fas fa-user",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,

    "custom_css": None,
    "custom_js": None,

    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "api.book": "collapsible",
        "api.loan": "single",
    },
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",

    "navbar_small_text": False,
    "footer_small_text": False,

    "navbar_fixed": True,
    "layout_boxed": False,

    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "theme_colour": "navbar-dark",

    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}